erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER {
        string name PK
        string sector
    }
    ORDER {
        int orderNumber PK
        string deliveryAddress FK
    }
