stateDiagram-v2
    [*] --> Active
    state Active {
        [*] --> NumLockOff
        NumLockOff --> NumLockOn: toggle
        --
        [*] --> CapsLockOff
        CapsLockOff --> CapsLockOn: toggle
    }
    Active --> [*]
